apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digitalocean-exporter.fullname" . }}
  labels:
    {{- include "digitalocean-exporter.labels" . | nindent 4 }}
stringData:
  DIGITALOCEAN_TOKEN: {{ required "Value exporter.DIGITALOCEAN_TOKEN is not configured!" .Values.exporter.DIGITALOCEAN_TOKEN | quote }}
  {{- range $key, $value :=  .Values.exporter }}
  {{- if ne $key "DIGITALOCEAN_TOKEN" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

