apiVersion: v1 
kind: ConfigMap 
metadata:
  name: {{ include "float-exporter.fullname" . }}-config
  labels:
    {{- include "float-exporter.labels" . | nindent 4 }}
data:
  float_exporter.yml: |
    email: {{ required "A valid .Values.email entry required!" .Values.email | quote }}
    user_agent: {{ print .Values.userAgent " " .Chart.AppVersion | quote }}
    log_level: {{ .Values.logLevel | quote }}
    port: {{ .Values.service.port }}
    report_days: {{ .Values.reportDays }}

