apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-backup.fullname" . }}
  labels:
    {{- include "db-backup.labels" . | nindent 4 }}
stringData:
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  backups.yaml: |
    {{- with .Values.backups }}
    {{- toYaml . | nindent 4 }}
    {{- end }}



